url: https://adye20.github.io
baseurl:

# Site settings
title: Andrew M. Dye
email: adye20@gmail.com
description: "Andrew Dye. Full stack web developer. Electrical Engineer. Hockey and golf aficionado. Innovative, enthusiastic, adaptable, driven."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F47940
  secondary: f46c40
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/adye20
  - title: facebook
    url: https://www.facebook.com/adye20
  - title: linkedin
    url: https://www.linkedin.com/in/andrewmdye
  - title: github
    url: https://github.com/adye20
  - title: google-plus
    url: https://plus.google.com/117846537449860335746/posts

# Postal address (add as many lines as necessary)
address:
  - line: 1486 Triumph Ct.
  - line: San Jose CA 95129

# Build settings
markdown: kramdown
permalink: pretty